function [PEst,ObjEst,Hess] = mymin(Func,P0,Low,Upp,OptimSet)

OptimSet = [OptimSet,{ ...
    'display','iter', ...
    'algorithm','active-set', ...
    'tolFun',1e-6, ...
    'tolX',1e-6, ...
    }];
oo = optimset(OptimSet{:});

[PEst,ObjEst,Hess] = fmincon(Func,P0,[],[],[],[],Low,Upp,[],oo);

end